# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: MyCustomAgentPool

steps:
- script: |
    make install
    make lint
  displayName: 'Build'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to App Service'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(021bd9db-07a7-4960-8a76-41c351b5bfb8)'
    appType: 'webAppLinux'
    WebAppName: 'flask-ml-azure-cicd'
    packageForLinux: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
